name: Tag Version After Checks

# Only works in main branch
on:
    workflow_run:
      workflows: ["Package Tests"]
      types:
        - completed

jobs:
  tag-version:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toml

      - name: Extract version and Tag
        id: extract_version
        run: |
            echo "Extracting version..."
            version=$(python -c "import toml; pyproject = toml.load('pyproject.toml'); print(pyproject['project']['version'])")
            echo "VERSION=$version" >> $GITHUB_ENV
            echo "The version is $version"

            echo "Configuring Git user..."
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            
            echo "Creating and pushing tag for version $version..."
            git tag "$version"
            git push origin "$version"