name: Tag Version After Checks

on:
  workflow_run:
    workflows: ["Check Version Bump", "Python Package"]
    branches: [main]
    types:
      - completed

jobs:
  tag-version:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toml

      - name: Extract version
        id: extract_version
        run: |
          echo "Extracting version..."
          version=$(python -c "import toml; pyproject = toml.load('pyproject.toml'); print(pyproject['project']['version'])")
          echo "VERSION=$version" >> $GITHUB_ENV
      
      - name: Tagging
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Creating tag for version ${{ env.VERSION }}"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}
