name: Tag Version After Checks

on:
    pull_request:
      branches:
        - main

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toml

      - name: Extract version
        id: extract_version
        run: |
          echo "Extracting version..."
          version=$(python -c "import toml; pyproject = toml.load('pyproject.toml'); print(f" Version Number: {pyproject['project']['version']}")
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "The version is ${{ env.VERSION }}"
